### PR TITLE
Rename `typeLocation` to `parameter` to better reflect its usage

### PR DESCRIPTION
**Pull request by hainest**
This just reflects our movement away from information derived from location lists to more agnostic representations of ABIs.

### CODE REVIEW

**Comment by hainest** [comment]
Bah, my interactive rebase removed a couple of changes. Grumble... Let me fix that.

**Comment by vsoch** [comment]
Does this change compile for you? I'm getting:

```
[ 28%] Building CXX object _deps/smeagle-build/CMakeFiles/Smeagle.dir/source/corpora.cpp.o
/code/source/corpora.cpp: In member function 'void smeagle::Corpus::toAsp()':
/code/source/corpora.cpp:26:26: error: 'typelocs' was not declared in this scope
     for (auto &typeloc : typelocs) {
                          ^~~~~~~~
/code/source/corpora.cpp:26:26: note: suggested alternative: 'typeloc'
     for (auto &typeloc : typelocs) {
                          ^~~~~~~~
                          typeloc
/code/source/corpora.cpp:28:30: error: 'p' was not declared in this scope
                   << ", " << p.name << ", " << p.type << ", \""
                              ^
/code/source/corpora.cpp: In member function 'void smeagle::Corpus::toYaml()':
/code/source/corpora.cpp:38:26: error: 'typelocs' was not declared in this scope
     for (auto &typeloc : typelocs) {
                          ^~~~~~~~
/code/source/corpora.cpp:38:26: note: suggested alternative: 'typeloc'
     for (auto &typeloc : typelocs) {
                          ^~~~~~~~
                          typeloc
/code/source/corpora.cpp:40:39: error: 'p' was not declared in this scope
                   << "\n   name: " << p.name
                                       ^
/code/source/corpora.cpp: In member function 'void smeagle::Corpus::toJson()':
/code/source/corpora.cpp:63:24: error: 'struct smeagle::parameter' has no member named 'parent'
                   << p.parent << "\", \"name\": \"" << p.name << "\", \"type\": \""
                        ^~~~~~
/code/source/corpora.cpp:65:46: error: 'struct smeagle::parameter' has no member named 'reg'
                   << "\"register\": \"" << p.reg << "\"}"
                                              ^~~
_deps/smeagle-build/CMakeFiles/Smeagle.dir/build.make:75: recipe for target '_deps/smeagle-build/CMakeFiles/Smeagle.dir/source/corpora.cpp.o' failed
make[3]: *** [_deps/smeagle-build/CMakeFiles/Smeagle.dir/source/corpora.cpp.o] Error 1
make[3]: Leaving directory '/code/build'
CMakeFiles/Makefile2:301: recipe for target '_deps/smeagle-build/CMakeFiles/Smeagle.dir/all' failed
make[2]: *** [_deps/smeagle-build/CMakeFiles/Smeagle.dir/all] Error 2
make[2]: Leaving directory '/code/build'
Makefile:145: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/code/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by vsoch** [comment]
ah just saw your comment! Gotcha.

**Comment by hainest** [comment]
@vsoch It's those dang ghosts again! Should work now. :D

**Review by vsoch — APPROVED** [review]

**Pull request merged**
