### PR TITLE
Refactor/register classes

### PR DESCRIPTION
**Pull request by vsoch**
This will merge our recent work into the current main. I suspect there will be merge conflicts and I'll try to manage them after opening the PR.

### CODE REVIEW

**Review by hainest — APPROVED** [review]
LGTM!

I also noticed that `make test` now is able to run the unit tests without trouble. How did you fix the library lookup issue?

**Comment by vsoch** [comment]
@hainest I have no idea. :laughing:

**Comment by vsoch** [comment]
I think there is probably a set of ancestral ghosts that follow me around and mind-meld me and then *pouf* magically compilation or dependency problems go away! :ghost: Or... maybe you fixed it?

**Comment by hainest** [comment]
Weird! I didn't do anything. I also just verified that it works in the container. :shrug:

**Pull request merged**
