### PR TITLE
Remove unused includes

### PR DESCRIPTION
**Pull request by hainest**

### CODE REVIEW

**Comment by vsoch** [comment]
This looks good! Does c++ have something akin to isort / pyflakes that could detect this?

**Comment by hainest** [comment]
@vsoch https://include-what-you-use.org/

**Comment by vsoch** [comment]
ooh lala! And look what I found! https://github.com/marketplace/actions/include-what-you-use-github-action. I'll see if I can add it.

**Review by vsoch — APPROVED** [review]

**Comment by hainest** [comment]
Oh, very nice! We should definitely use that. I'll also look at adding it to Dyninst's actions.

**Pull request merged**
